name: k_chart_multiple
description: A Flutter K Chart support multiple secondary chart.
version: 1.3.0
homepage: https://github.com/Aressssssssssssss/k_chart_multiple

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
